[advisories]
ignore = [
    # False positive: rsa is pulled as an optional unused dependency by sqlx-mysql (which is pulled by sqlx-macros)
    # We are using PostgreSQL exclusively, so this code path is never compiled nor executed in our binaries.
    "RUSTSEC-2023-0071",
    
    # Warning: fxhash is unmaintained, but it's deeply nested in our html scraper dependencies (selectors). 
    # It does not pose a direct security risk for our usage context.
    "RUSTSEC-2025-0057"
]