-- Migration 20260304_042_seed_mcp_servers
-- Autogenerated Seed for global MCP Tool ecosystem for GeminiHydra Swarm

INSERT INTO gh_mcp_servers (id, name, transport, command, args, env_vars, url, enabled, timeout_secs)
VALUES
    (gen_random_uuid(), 'serena', 'stdio', 'uvx', 
    '["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex", "--project", "C:/"]', 
    '{}', NULL, true, 30),

    (gen_random_uuid(), 'desktop-commander', 'stdio', 'npx', 
    '["-y", "@wonderwhy-er/desktop-commander"]', 
    '{"DC_SHELL": "powershell"}', NULL, true, 30),

    (gen_random_uuid(), 'playwright', 'stdio', 'npx', 
    '["-y", "@playwright/mcp@latest"]', 
    '{}', NULL, true, 30),

    (gen_random_uuid(), 'brave-search', 'stdio', 'cmd', 
    '["/c", "npx", "-y", "@modelcontextprotocol/server-brave-search"]', 
    '{"BRAVE_API_KEY": "BSAXJ2S-GwXLGx8yHnaMJ2cX1w51DRi"}', NULL, true, 30),

    (gen_random_uuid(), 'repomix', 'stdio', 'cmd', 
    '["/c", "npx", "-y", "repomix", "--mcp"]', 
    '{}', NULL, true, 30),

    (gen_random_uuid(), 'filesystem', 'stdio', 'cmd', 
    '["/c", "npx", "-y", "@modelcontextprotocol/server-filesystem", "C:\\Users\\BIURODOM\\Desktop"]', 
    '{}', NULL, true, 30),

    (gen_random_uuid(), 'memory', 'stdio', 'cmd', 
    '["/c", "npx", "-y", "@modelcontextprotocol/server-memory"]', 
    '{"MEMORY_FILE_PATH": "C:\\Users\\BIURODOM\\Desktop\\SharedMemory\\memory.json"}', NULL, true, 30),

    (gen_random_uuid(), 'sequential-thinking', 'stdio', 'cmd', 
    '["/c", "npx", "-y", "@modelcontextprotocol/server-sequential-thinking"]', 
    '{}', NULL, true, 30),

    (gen_random_uuid(), 'context7', 'stdio', 'cmd', 
    '["/c", "npx", "-y", "@upstash/context7-mcp@latest"]', 
    '{}', NULL, true, 30)
ON CONFLICT (name) DO UPDATE SET
    transport = EXCLUDED.transport,
    command = EXCLUDED.command,
    args = EXCLUDED.args,
    env_vars = EXCLUDED.env_vars,
    enabled = EXCLUDED.enabled;

-- Special insert for HTTP/SSE based GitHub MCP
INSERT INTO gh_mcp_servers (id, name, transport, command, args, env_vars, url, auth_token, enabled, timeout_secs)
VALUES
    (gen_random_uuid(), 'github', 'http', NULL, '[]', '{}', 
    'https://api.githubcopilot.com/mcp/', '<YOUR_GITHUB_TOKEN>', true, 30)
ON CONFLICT (name) DO UPDATE SET
    transport = EXCLUDED.transport,
    url = EXCLUDED.url,
    auth_token = EXCLUDED.auth_token;