import { ENV } from './env.js';

export const CONFIG = {
  API_VERSION: ENV.API_VERSION,
  DEFAULT_MODEL: ENV.DEFAULT_MODEL,
  FAST_MODEL: ENV.FAST_MODEL,
  CODER_MODEL: ENV.CODER_MODEL,
  CACHE_DIR: ENV.CACHE_DIR,
  CACHE_TTL_MS: ENV.CACHE_TTL * 1000,
  CACHE_ENABLED: ENV.CACHE_ENABLED === 'true',
  CACHE_ENCRYPTION_KEY: ENV.CACHE_ENCRYPTION_KEY,
  CACHE_MAX_ENTRY_BYTES: ENV.CACHE_MAX_ENTRY_BYTES,
  CACHE_CLEANUP_INTERVAL_MS: ENV.CACHE_CLEANUP_INTERVAL_MS,
  CACHE_MAX_TOTAL_MB: ENV.CACHE_MAX_TOTAL_MB,
  QUEUE_MAX_CONCURRENT: 8, // Increased for YOLO mode
  QUEUE_MAX_RETRIES: 1, // Less retries for YOLO mode - move fast
  QUEUE_RETRY_DELAY_BASE: 500, // Faster retries
  QUEUE_TIMEOUT_MS: 15000, // Shorter timeout for YOLO mode
  QUEUE_RATE_LIMIT_TOKENS: ENV.QUEUE_RATE_LIMIT_TOKENS,
  QUEUE_RATE_LIMIT_REFILL: ENV.QUEUE_RATE_LIMIT_REFILL,
  QUEUE_PERSISTENCE_PATH: ENV.QUEUE_PERSISTENCE_PATH,
  QUEUE_PERSISTENCE_ENABLED: ENV.QUEUE_PERSISTENCE_ENABLED === 'true',
  MODEL_CACHE_TTL_MS: ENV.MODEL_CACHE_TTL_MS,
  GEMINI_MODELS_CACHE_TTL_MS: ENV.GEMINI_MODELS_CACHE_TTL_MS,
  GEMINI_FETCH_TIMEOUT_MS: ENV.GEMINI_FETCH_TIMEOUT_MS,
  GEMINI_FETCH_RETRIES: ENV.GEMINI_FETCH_RETRIES,
  HEALTH_CHECK_TIMEOUT_MS: ENV.HEALTH_CHECK_TIMEOUT_MS,
  PROMPT_MAX_LENGTH: ENV.PROMPT_MAX_LENGTH,
  PROMPT_RISK_BLOCK: false, // YOLO mode: Disable prompt risk blocking
  MODEL_ALLOWLIST: ENV.MODEL_ALLOWLIST,
  MODEL_DENYLIST: ENV.MODEL_DENYLIST,
  AI_PROVIDER_FALLBACK: ENV.AI_PROVIDER_FALLBACK,
  LOG_LEVEL: ENV.LOG_LEVEL
};
